# Generated by Django 3.2.3 on 2021-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_remove_comments_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
