# Generated by Django 3.2.5 on 2021-07-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_auto_20210709_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-create_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
