# Generated by Django 3.2.3 on 2021-07-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bicycles', '0002_auto_20210114_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsles',
            name='wheels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bicycles.wheels', verbose_name='Колеса'),
        ),
    ]
