# Generated by Django 3.2.3 on 2021-07-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_auto_20210112_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transmissions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
